CREATE TABLE IF NOT EXISTS asu_classes (
    id SERIAL PRIMARY KEY,
    course_prefix VARCHAR(255) ,
    course_stack VARCHAR(255),
    course_stack_full_form VARCHAR(255),
    course_name VARCHAR(255),
    course_code VARCHAR(255) UNIQUE,
    session VARCHAR(255),
    term VARCHAR(255),
    faculty VARCHAR(10000),
    college VARCHAR(255),
    department VARCHAR(255),
    seat_info_enrl_cap INT,
	seat_info_enrl_tot INT,
    address VARCHAR(255),
	map_url VARCHAR(255),
    campus VARCHAR(255),
    campus_descr VARCHAR(255),
    acad_career VARCHAR(255),
    hours VARCHAR(255),
    start_date TIMESTAMP,
    start_time VARCHAR(255),
    end_date TIMESTAMP,
    end_time VARCHAR(255),
    day_list VARCHAR(255)
);